export user="admin"
export password="supersecret"
export influx_token="token"
export influx_bucket="bucket_name"
export influx_org="org_name" 
export influx_port="8086"
export influx_server="localhost"
export grafana_port="3000"
